### ISSUE TITLE
Great Example!

### ISSUE THREAD

**Issue by ychakiris** [apofiget/c_node_ex#1]
This is a VERY useful example. Did you put this together based on some live production example or just as an exercise?

**Comment by apofiget** [comment]
Hey!
No, this code is just exercise, but with some changes may be used in production. I hope :)
I think this technique may be used when you need isolate mission critical Erlang code from unstable C-code which can crash or something like this.  I wrote another example, in which i've read IP packets via netfilter queue API, and sent in to Erlang node for a analyze and making decision about forwarding.

**Comment by apofiget** [comment]
Closed.
